name: Simple Build Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: A simple step to prove the pipeline runs
        run: echo "The pipeline has successfully started and this step works!"
